# Generated by Django 4.1.2 on 2022-11-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_gallery_image_chef_type_gallery_img_menu_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(default='images/blog.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='photo',
            field=models.ImageField(default='images/chef.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(default='images/chef.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(default='images/item.jpg', upload_to='images/'),
        ),
    ]
