# Generated by Django 3.2.16 on 2022-12-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_blog_banner_alter_chef_photo_alter_gallery_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='facebook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='linkedin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='twitter',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
