# Generated by Django 4.1.2 on 2022-11-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='kind',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Meals', 'Meals'), ('Snacks', 'Snacks'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks')], max_length=10),
        ),
    ]
