# Generated by Django 4.1.2 on 2022-11-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog_chef_contact_gallery_reservation_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
