# Generated by Django 4.1.2 on 2022-11-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AddField(
            model_name='chef',
            name='type',
            field=models.CharField(blank=True, choices=[('Head', 'Head'), ('Pizza', 'Pizza'), ('Grill', 'Grill'), ('Burger', 'Burger')], max_length=20),
        ),
        migrations.AddField(
            model_name='gallery',
            name='img',
            field=models.ImageField(default='images/chef.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.ImageField(default='images/item.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(default='images/blog.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='photo',
            field=models.ImageField(default='images/chef.jpg', upload_to='images'),
        ),
    ]
